name: Test Circuit Execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install circom
      run: |
        curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
        source ~/.cargo/env
        git clone https://github.com/iden3/circom.git
        cd circom
        cargo build --release
        cargo install --path circom

    - name: Install snarkjs
      run: npm install -g snarkjs

    - name: Compile circuits
      run: |
        cd circuits
        ~/.cargo/bin/circom multiplier2.circom --r1cs --wasm --sym
        ~/.cargo/bin/circom simpleCheck.circom --r1cs --wasm --sym

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Test multiplier2 circuit
      run: cargo run multiplier2

    - name: Test simpleCheck circuit
      run: cargo run simpleCheck