name: Test Circuit Execution

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Test multiplier2 circuit
      run: cargo run multiplier2

    - name: Test simpleCheck circuit
      run: cargo run simpleCheck